# Generated by Django 2.2.2 on 2019-06-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ID', models.CharField(blank=True, default='', max_length=100)),
                ('Name', models.TextField()),
                ('Speaker', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
